.TH i8kctl 1 2014-08-09 "Vitor Augusto"
.SH "NAME"
.LP
i8kctl \- Utility to define and retrieve information about the fans states and
speeds on Dell laptops.
.SH "SYNOPSIS"
\fBi8kctl\fP [\fI<param>\fP [\fI<args>\fP]]
.SH "DESCRIPTION"
.LP
The i8kctl utility provides a command\-line interface to retrieve one of the
information listed below. It does that by means of querying the system through
the i8k kernel module. When invoked without arguments it reports all the
information at once in one line of text. These information are the same
contained in the file \fB/proc/i8k\fR.
.IP
1.  i8k output format version
.br
2.  Dell bios version
.br
3.  service tag (later 'machine id')
.br
4.  cpu temperature
.br
5.  left fan status
.br
6.  right fan status
.br
7.  left fan speed
.br
8.  right fan speed
.br
9.  ac power status
.br
10. fn buttons status
.LP
The following parameters are used to select one of the
items above: \fBversion\fR, \fBbios\fR, \fBid\fR,
\fBtemp\fR, \fBfan\fR, \fBspeed\fR, \fBac\fR and \fBfn\fR.
.LP
Some examples of usage and output are below.
.IP
$ i8kctl
.br
1.0 A17 B5W123K 52 2 1 8040 6420 1 2
.IP
$ i8kctl temp
.br
52
.IP
$ i8kctl fan
.br
2 1
.LP
The \fBfan\fR parameter accepts two optional arguments for the fans
states. The state arguments can be:
.IP
0  turn the fan off
.br
1  set low speed
.br
2  set high speed
.br
\-  don't change the state of this fan
.LP
And the following is an example of usage:
.IP
$ i8kctl fan \- 2
.LP
This sets the right fan to high speed and leaves the left unchanged.
It should be noted that if the \fBi8kmon(1)\fR daemon is used to
control the fans, setting the speed with \fBi8kctl fan\fP is pointless since the
daemon override regularly the speed with its own value.
.LP
If \fBi8kctl fan\fR is invoked without the optional arguments, the states
of the fans are returned, and the output may contains a -1 which indicates that the
corresponding fan does not exist.
.SH "FILES"
.LP
\fI/proc/i8k\fP
.SH "AUTHORS"
.LP
2013-2015 Vitor Augusto <vitorafsr@gmail.com>
.br
2001-2009 Massimo Dal Zotto <dz@debian.org>
.SH "COPYRIGHT"
.LP
i8kctl is part of the i8kutils package. All files are distributed under the GNU
General Public License (GPL). On Debian GNU/Linux systems, the complete text of
the GNU General Public License can be found in `/usr/share/common-licenses/GPL'.
.SH "SEE ALSO"
.LP
i8kmon(1)
