.TH i8kui 1 "08 Dec 2014"
.\" Please update the above date whenever this man page is modified.
.SH NAME
i8kui \- User interface for i8kutils
.SH SYNOPSIS
.B i8kui
.SH DESCRIPTION
\fBi8kui\fP is a graphical tool that shows the CPU temperature and has buttons
to control the fans speed. It is a small applet originally developed to
be embeded in gnome panel. But can be used as a standalone window.
.LP
The temperature is shown in the upper part of the window with value as read by
"i8kctl temp" command. The background color of the display is
according to the temperature. The temperature value can be displayed in °C or
°F. Default is Celsius.
.LP
The number of buttons below the display depends on the number of fans: one
button for each fan. On pressing a button, the fan speed changes cyclically
from speed 0 (stopped) to speed 2 (highest).
.SH OPTIONS
i8kui does not accept command line args but a set of variables can be set in
i8kutils system configuration file or user configuration file. The files are
located as specified in \fBFILES\fP section.
.SH CUSTOMIZATION
The variables and values that can be put in configuration files are:
.TP
\fBset config(sysconfig)\fR   /etc/i8kmon.conf
System configuration file
.TP
\fBset config(userconfig)\fR  ~/.i8kmon
User configuration file
.TP
\fBset config(verbose)\fR 0
Print verbose logs
.TP
\fBset config(timeout)\fR 5
Update interval
.TP
\fBset config(unit)\fR    C
Unit of measure
.TP
\fBset config(t_high)\fR  80
High temperature
.SH FILES
\fI/etc/i8kmon.conf\fP
.br
\fI/$HOME/.i8kmon\fP
.SH "SEE ALSO"
.BR i8kctl (1)
.SH AUTHOR
Vitor Augusto <vitorafsr@gmail.com>.
